name: ci

env:
 CI: true

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Go to frontend directory
        run: cd frontend
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install packages
        run: yarn install
      - name: Build app
        run: CI=false yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push'
        with:
          keepFiles: false
        env:
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./build
          github_token: ${{ secrets.GITHUB_TOKEN }}
